[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agency-code"
version = "1.0.0"
description = "An intelligent AI development assistant powered by Claude with built-in safety architecture"
readme = "README.md"
requires-python = ">=3.13"
license = {text = "MIT"}
authors = [
    {name = "Joseph Pichardo", email = "joeyjoe808@users.noreply.github.com"}
]
maintainers = [
    {name = "Joseph Pichardo", email = "joeyjoe808@users.noreply.github.com"}
]
keywords = [
    "ai",
    "claude",
    "agent",
    "developer-assistant",
    "cli",
    "anthropic",
    "multi-agent",
    "code-generation",
    "ai-assistant"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Environment :: Console",
]

dependencies = [
    "openai-agents[litellm]==0.4.1",
    "litellm>=1.0.0",
    "beautifulsoup4>=4.9.0",
    "python-dotenv>=0.19.0",
    "pydantic>=2.0.0",
    "requests>=2.25.0",
    "dulwich>=0.21.6",
]

# Note: agency-swarm must be installed separately from git
# pip install git+https://github.com/VRSEN/agency-swarm.git@main

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-asyncio>=0.21.0",
]

[project.urls]
Homepage = "https://github.com/joeyjoe808/Agent-C"
Documentation = "https://github.com/joeyjoe808/Agent-C/blob/main/ASKME.md"
Repository = "https://github.com/joeyjoe808/Agent-C.git"
Issues = "https://github.com/joeyjoe808/Agent-C/issues"

[project.scripts]
aria = "agency:main"

[tool.setuptools]
py-modules = ["agency"]
packages = [
    "agency_code_agent",
    "planner_agent",
    "subagent_example",
    "tools",
    "safety",
    "shared",
]

[tool.setuptools.package-data]
"*" = ["*.md", "*.txt"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
asyncio_mode = "auto"
